### ISSUE TITLE
Make 'team' page in dev.js

### ISSUE THREAD

**Issue by vivekpal1** [Shastra-OS/site#55]
Make Team page for ShastraOS website.
This will include -
- Profile of Developers and Contributers
- Styling shoud match wesbsite styling overall
- For now you can add [me](https://github.com/vivekpal1)
- Profile will inculde, Github, Twitter, Website  and profile picture from github, https://github.com/username.png 
- https://github.com/vivekpal1.png in my case

**Comment by nooras** [comment]
Interested please assign to me if no one working on it. Thanks

**Comment by adityyaa-10** [comment]
Can I work on this?

**Comment by nooras** [comment]
Hi @vivekpal1 do we need to work on this together ?

**Comment by nooras** [comment]
Hi @vivekpal1 

Can you please check the PR. Let us know if any changes are required.
If its fine and some more changes are required then I or @adityyaa-10 can work on it.
