### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by Oussamaosman02** [Shastra-OS/site#56]
I have seen the code and the package.json have some old versions that might be updated.
This are the suggested changes:
| package | version used | recommended version| type |
| ----------- | ----------------- | ----------------------------- | ------ |
| @typeform/embed-react | 1.21.0 | 2.1.0 | **major** |
| next | 12.1.0 | 12.3.1 | minor |
| next-pwa | 5.5.4 | 5.6.0 | minor |
| react | 17.0.2 | 18.2.0 | **major** |
| react-dom | 17.0.2 | 18.2.0 | **major** |
| react-icons | 4.3.1 | 4.4.0 | minor |

But, with the updated dependecies, `react-device-mockups` and `react-mockup` trhow me an error while trying to install them

**Comment by vivekpal1** [comment]
Udated 🫡
