### ISSUE TITLE
Top most content is not visible 

### ISSUE THREAD

**Issue by adityyaa-10** [Shastra-OS/site#76]
### Due to the fixed Navbar, the top most content, i.e., the headings of the pages are not properly visible 

👇🏻👇🏻

![Screenshot from 2022-10-16 01-06-59](https://user-images.githubusercontent.com/103577578/196004955-e5c89cd1-aa43-41aa-99e8-3ac7fa1cd991.png)
![Screenshot from 2022-10-16 01-07-15](https://user-images.githubusercontent.com/103577578/196004958-0d40c53f-7ce5-4dfc-a4db-138b1f369c61.png)

**Comment by vivekpal1** [comment]
Ya, I also noticed it.
Well I am assigning you, if you want to fix.
