### ISSUE TITLE
[Header] Create a responsive navbar

### ISSUE THREAD

**Issue by Mukul108** [Shastra-OS/site#86]
It sucks in mobile,
![Screenshot from 2022-10-17 21-46-12](https://user-images.githubusercontent.com/82668326/196229496-d144169a-8230-49f3-a21b-444099f9c9b6.png)
![Screenshot from 2022-10-17 21-45-38](https://user-images.githubusercontent.com/82668326/196229518-35b6881d-2cc2-4c4f-9f5d-ec650a438ba9.png)

Like this one 
![Screenshot from 2022-10-17 21-48-02](https://user-images.githubusercontent.com/82668326/196229836-5070e8bd-8ca4-4a66-bc80-df8183e8e39c.png)

**Comment by avezqureshi14** [comment]
can you assigned this to me

**Comment by adityyaa-10** [comment]
I would like to work on this
