### ISSUE TITLE
[BUG] Shastra OS card overlaps text

### ISSUE THREAD

**Issue by slim-codes** [Shastra-OS/site#87]
- The container containing the 3 scrolling cards is overlapping the text above it.

![Screenshot from 2022-10-17 18-49-51](https://user-images.githubusercontent.com/72257135/196247572-643a6a75-7fcd-4481-bc05-9d593b21aa03.png)

- The page should look like this:

![Screenshot from 2022-10-17 18-56-21](https://user-images.githubusercontent.com/72257135/196248672-f5b6c70d-8e2d-4e80-83da-62d561da75ab.png)

**Comment by vivekpal1** [comment]
Thanks for reporting,
Do you want to work on this?

**Comment by slim-codes** [comment]
Sure! Working on it

Tee
