### ISSUE TITLE
NPM Install throwing error

### ISSUE THREAD

**Issue by slim-codes** [Shastra-OS/site#94]
Error shown after running NPM install

- Environment - Ubuntu (Linux)
- I just encountered an issue while working on issue #87 

![Screenshot from 2022-10-19 22-37-06](https://user-images.githubusercontent.com/72257135/196799352-9985d7b1-c1d0-4606-807c-638e06b0c979.png)

![Screenshot from 2022-10-19 22-35-59](https://user-images.githubusercontent.com/72257135/196799362-5acaad20-f44c-4093-8b7b-e8d798d9b5c2.png)

**Comment by vivekpal1** [comment]
Try this command

```bash
npm config set legacy-peer-deps true
```
or install through this command
```bash
npm install --save --legacy-peer-deps
```

You can also look at [legacy-peer-deps](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps)

**Comment by slim-codes** [comment]
Thanks! It worked
